### ISSUE TITLE
[Question] Do reoriented contigs match the strandedness of the balst result?

### ISSUE THREAD

**Issue by rpetit3** [gbouras13/dnaapler#41]
Hi @gbouras13!

Does the reoriented contig match the strandedness of the blast result? Or is it always positive?

This stems from https://github.com/rpetit3/dragonflye/issues/22 where I plan to add dnaapler as a final step.

Thank you so much! 
Robert

Also, I think I found the spot in the code where it happens, but wanted to make sure! Your code was so nice! And, the comments for very helpful, thank you for that!

**Comment by gbouras13** [comment]
Hi @rpetit3 

Thanks for the kind words mate!!

Yes, Dnaapler does always make the reoriented contig start (with dnaa) in the positive direction by design.

If that isn't suitable I can create a new subcommand for use with dragonflye, it shouldn't be too hard.

I'd imagine you want `dnaapler all` in dragonflye in case you have multiple contigs/plasmids etc.

There is a hierarchy: if multiple hits are found: 1)  dnaA, 2) repA then 3) terL (which is likely on chromosomes if you have prophages).

The spot is here https://github.com/gbouras13/dnaapler/blob/8c55731b6790dee3c34b97c6cebd34e702606351/src/dnaapler/utils/processing.py#L221C1-L228C27

If you need any other advice or help integrating it into dragonflye please let me know.

PS Sorry to change topic but while I have you, if you know who or where to go with this, I'd love some help https://github.com/bioconda/bioconda-recipes/pull/42998 - only because I know you'd know better than me with bioconda! 

I want to incorporate ALE into my hybracter scalable pipeline to estimate whether polishing improved the assembly. It could even be interesting to consider with dragonflye too perhaps. But we need a non-broken release on bioconda!

George

**Comment by rpetit3** [comment]
@dfornika this sound like what you were looking for?

@gbouras13 I'll definitely take a look at this bioconda PR! (as in now haha)

**Comment by dfornika** [comment]
Yeah, this sounds great to me. I've been meaning to test out dnaapler a bit but haven't found the time to set anything up yet. But this sounds very similar to the functionality that unicycler has, which is what we're interested in replicating in our dragonflye assemblies.
