### ISSUE TITLE
[JOSS Review] - Documentation

### ISSUE THREAD

**Issue by vinisalazar** [gbouras13/dnaapler#48]
Hi,

attached are some suggestions for the documentation based on my review:

https://github.com/gbouras13/dnaapler/blob/7c67b3beb930c9e2a1e031612841bc7541aa6915/README.md?plain=1#L20

* Include `-c bioconda`, like in the command specified in Line 95 of the same file. This should prevent many first-time users from running into a "package not found" error, as it is unlikely they will have read the [Beginner Conda Installation](https://dnaapler.readthedocs.io/en/latest/install/) section of the docs. You may also link this section here.

https://github.com/gbouras13/dnaapler/blob/7c67b3beb930c9e2a1e031612841bc7541aa6915/README.md?plain=1#L106

* Specify that this is only required if installing with pip (would Prodigal be required too if the user wants to use the Pyrodigal commands?)

https://github.com/gbouras13/dnaapler/blob/7c67b3beb930c9e2a1e031612841bc7541aa6915/docs/install.md?plain=1#L46

* This list numbering is rendering incorrectly in the readthedocs page.

---

I will update this issue if I find anything else.

cc openjournals/joss-reviews#5968

**Comment by gbouras13** [comment]
Hi @vinisalazar ,

Thanks for these. Also linking to #51 regarding your third point as they will be dealt with together.

Your first point has been fixed in the READ.me to make it easier for beginners to follow - namely, by making an empty conda env and then installing dnaapler (I did not get good results trying to do it all in one line, therefore a beginner will have a harder time!).

The second point also has been fixed. 

To clarify, prodigal is not required dnaapler at all. This is because pyrodigal is a self contained Python package that reimplements and provides python bindings to Prodigal and therefore does not require it as a dependency. pyrodigal will always be installed with a pip install of dnaapler.

Regarding your third point, install.md is overhauled after #51 - the correct numbering will be used.

George

**Comment by mkerin** [comment]
This is a quick comment to say that I think there is an unfinished sentence on line 54 of `docs/example.md` here
https://github.com/gbouras13/dnaapler/blob/bf86601136951079218f258452f5ff40733d50f9/docs/example.md?plain=1#L54

I also think that, other than this typo, the new docs/example.md section is excellent.

**Comment by gbouras13** [comment]
Hi @mkerin,

Thanks for picking this up - I've made a fix now in the commit references above.

George

**Comment by vinisalazar** [comment]
LGTM @gbouras13.

I will close this issue for now but @mkerin or @gbouras13 please reopen it if you deem it necessary.
