### ISSUE TITLE
Option to specify start gene type in all mode

### ISSUE THREAD

**Issue by oschwengers** [gbouras13/dnaapler#63]
Hi @gbouras13,
thank you very much for this super useful tool - something that I very often considered to start developing myself ;-) So, thanks a lot for this!

I've seen that the `terL` DB of dnaapler is quite heavy compared to the `dnaA`/`repA`. Re-orientating (semi) finished bacterial genomes is a very common task. To save runtime in large-scale analyses, I guess it might be interesting/OK to skip the phage step for the majority of cases, since most phages would be inserted in a chrom/plasmid anyway and if not, it would be okish to have the phage not re-orientated. Trying  dnaapler on a genome of a novel species took ~15 min (for which it was not able to find a decent `dnaA` gene - most likely just lacking a closely related sequence to those within SwissProt ). Hence, I wonder if it would be possible and OK for you to provide an option either to explicitly skip the `terL` step or to provide an option to choose 1 or 2 of all 3 steps, maybe something like `--db [dnaa,repa,terl]` or `--type [chrom,plasmid,phage]`.

Looking forward to your thoughts - and thanks again!

**Comment by gbouras13** [comment]
Hi @oschwengers ,

I agree with this all - I've been benchmarking Hybracter lately and have found that the dnaapler part can be slower than I'd like as well so ideally it can be sped up.

I think I will just add a 'dnaapler all --skip_terl' flag to handle this case - realistically most users will want chromosome and plasmids from this mode. 

I might just wait a week or two, partially due to being pretty busy with other things at the moment and partially to not interfere with the JOSS review process that is happening for dnaapler.

George

**Comment by oschwengers** [comment]
Thanks a lot for considering this - it's very much appreciated! And of course, no rush - open source dev, especially of side projects, can be quite demanding. I'm looking forward to it and good luck with the JOSS review!
Cheers

**Comment by gbouras13** [comment]
Fixed by v0.5.1
