### ISSUE TITLE
Error with subset of samples in pipeline

### ISSUE THREAD

**Issue by KR0manova** [gbouras13/dnaapler#77]
I have added `dnaapler all` to my Snakemake pipeline. It runs without issue for most samples, but a small handful fail with an error. I have attached the log and input file for one such failing sample. Just in case, I also attached the config file for the dnaapler env. Python version in Conda environment: Python 3.12.3

Input (renamed to txt to upload)
[PP04977_pilon.fasta.txt](https://github.com/user-attachments/files/16246442/PP04977_pilon.fasta.txt)

Logfile:
[PP04977_dnaapler.fasta.log](https://github.com/user-attachments/files/16246443/PP04977_dnaapler.fasta.log)

dnaapler config file (renamed to txt to upload)
[dnaapler.yml.txt](https://github.com/user-attachments/files/16246432/dnaapler.yml.txt)

I see this in the log file:
`WARNING  | dnaapler.utils.processing:reorient_single_record_bulk:391 - The top blastx hit for the contig NODE_1079_ did not begin with a valid start codon.`

But the file ends with:
`  File "/ebio/abt6_projects/Pseudomonas5000/Snakemake/.snakemake/conda/bfcb9a24112daef50ea4c0b10c556be2_/lib/python3.12/site-packages/dnaapler/utils/processing.py", line 416, in reorient_single_record_bulk
    closest_gene_index = max(overlap_dict, key=lambda key: overlap_dict[key])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty`

I do not know how to interpret the stack traceback of the error at the end. Is it failing due to the lack of valid start codon? If the error is simply the result of dnaapler not being able to reorient this assembly, then that's fine, and I'll wait for the dnaapler version that fixes https://github.com/gbouras13/dnaapler/issues/76 . If not, I would be grateful for suggestions on how to troubleshoot this.

System info:
Ubuntu 20.04.6 LTS
64-bit
GNOME version 3.36.8

**Comment by gbouras13** [comment]
Hi @KR0manova ,

I had a look at this - the error is with contig NODE_3970_

The issue is that this contig is tiny and has no CDS at all (according to prodigal), and so when Dnaapler tries to find the CDS with the biggest overlap with the blast hit, it can't find anything.

While in my contig is too short to use with Dnaapler in my opinion (please filter all the tiny contigs out as I doubt they are circular - that is my solution for you here), it is plausible that a longer contig might start with some fragment of dnaA and cause this error so I will put in a fix.

George

**Comment by KR0manova** [comment]
Thank you so much for looking into it!
